name: logbook_app_093
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  mongo_dart: ^0.10.8
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

# Bagian Flutter (assets, fonts, dll)
flutter:
  uses-material-design: true

  # Mendaftarkan folder gambar
  assets:
    - assets/images/
    - .env